//Next-js Components
import Head from "next/head";
import { GiAvocado } from "react-icons/gi";

//Components
import Intro from "../components/Intro";
import Services from "../components/Services";
import { data } from "../data";

// Styles
import styles from "../styles/page_styles/Home.module.css";

export default function Home({ services }) {
  console.log(services);
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome to AVOCADO</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Intro />
      <Services services={services} />
    </div>
  );
}

export const getStaticProps = async () => {
  const services = data;
  return { props: { services } };
};
